<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact Email</title>
</head>
<body style="font-family: Arial, Helvetica, sans-serif; font-size:17px; background-color: #f4f4f4; padding: 20px; margin: 0;">

    <div style="max-width: 600px; margin: 0 auto; background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <h1 style="color: #333; text-align: center; border-bottom: 2px solid #007bff; padding-bottom: 10px;">Contact Email</h1>

        <p style="color: #555;">You have received a new contact email from your website. Here are the details:</p>

        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
                <td style="padding: 10px; font-weight: bold; color: #333;">Name:</td>
                <td style="padding: 10px; color: #555;">{{ $mailData['name'] }}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; font-weight: bold; color: #333;">Email:</td>
                <td style="padding: 10px; color: #555;">{{ $mailData['email'] }}</td>
            </tr>
            <tr>
                <td style="padding: 10px; font-weight: bold; color: #333;">Subject:</td>
                <td style="padding: 10px; color: #555;">{{ $mailData['subject'] }}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; font-weight: bold; color: #333;">Message:</td>
                <td style="padding: 10px; color: #555;">{{ $mailData['message'] }}</td>
            </tr>
        </table>

        <p style="color: #777; text-align: center;">Thank you for your attention.</p>

        <footer style="text-align: center; margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd;">
            <p style="font-size: 14px; color: #888;">This email was automatically generated by your website's contact form.</p>
        </footer>
    </div>

</body>
</html>
